name: Build

on:
    push:
        branches: [dev]

jobs:
    build:
        runs-on: dedicated-server
        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"
            - name: Install dependencies
              run: |
                  yarn remove @nitrots/nitro-renderer
                  yarn add git+https://git@git.krews.org/nitro/nitro-renderer#dev
                  yarn install
            - name: Build Nitro
              run: |
                  yarn build
            - name: Archive Artifacts
              uses: actions/upload-artifact@v2
              with:
                  path: |
                      build
